export const darkColors = {
  background: '#0F0F1A',
  card: '#1A1A2E',
  cardElevated: '#242442',
  primary: '#6C63FF',
  primaryLight: '#8B85FF',
  primaryDark: '#5A52E0',
  secondary: '#00D4AA',
  secondaryLight: '#33DDBB',
  danger: '#FF6B6B',
  dangerLight: '#FF8A8A',
  warning: '#FFD93D',
  warningLight: '#FFE066',
  success: '#00D4AA',
  textPrimary: '#FFFFFF',
  textSecondary: '#8B8BA7',
  textTertiary: '#5A5A7A',
  border: '#2A2A4A',
  inputBackground: '#1E1E36',
  overlay: 'rgba(0, 0, 0, 0.6)',
  shimmerBase: '#1A1A2E',
  shimmerHighlight: '#2A2A4A',
  tabBar: '#141428',
  gradientStart: '#6C63FF',
  gradientEnd: '#3B82F6',
  statusBar: 'light-content' as const,
};

export const lightColors = {
  background: '#F5F5FA',
  card: '#FFFFFF',
  cardElevated: '#F0F0F8',
  primary: '#6C63FF',
  primaryLight: '#8B85FF',
  primaryDark: '#5A52E0',
  secondary: '#00D4AA',
  secondaryLight: '#33DDBB',
  danger: '#FF6B6B',
  dangerLight: '#FF8A8A',
  warning: '#FFD93D',
  warningLight: '#FFE066',
  success: '#00D4AA',
  textPrimary: '#1A1A2E',
  textSecondary: '#6B6B8A',
  textTertiary: '#9B9BB5',
  border: '#E0E0F0',
  inputBackground: '#F0F0FA',
  overlay: 'rgba(0, 0, 0, 0.4)',
  shimmerBase: '#E8E8F0',
  shimmerHighlight: '#F5F5FA',
  tabBar: '#FFFFFF',
  gradientStart: '#6C63FF',
  gradientEnd: '#3B82F6',
  statusBar: 'dark-content' as const,
};

export type AppColors = typeof darkColors;
